name: my first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome message
        run: echo "My firstgithub Actions job"

      - name: Checkout
        uses: actions/checkout@v4

      - name: list files
        run: ls

      - name: List Files
        run: ls
